### ISSUE TITLE
Cro uploads generate incorrect link

### ISSUE THREAD

**Issue by lizmat** [skaji/perl6-cpan-new#1]
On https://twitter.com/perl6_cpan_new , a recent bunch of uploads of Jonathan seems to create incorrect links.

    https://modules.perl6.org/dist/cro::zeromq:cpan:JNTHN

should be:

    https://modules.perl6.org/dist/Cro::ZeroMQ:cpan:JNTHN

Somehow the module names seems to get lowercased.  This only seems to happen with some Cro modules, but not all.

**Comment by skaji** [comment]
thanks. I’ll fix this.
