### ISSUE TITLE
Seems pushes are no longer tweeted??

### ISSUE THREAD

**Issue by lizmat** [skaji/perl6-cpan-new#2]
https://twitter.com/perl6_cpan_new  seems to have stopped on May 19.  Many uploads where done by me since then :-)

**Comment by skaji** [comment]
```
2018/05/20 10:27:40 503 unable to get max for perl.cpan.uploads
```

**Comment by skaji** [comment]
I restarted it for the time being.

**Comment by skaji** [comment]
@lizmat thanks for reporting this.

**Comment by skaji** [comment]
please reopen this issue if it stops again.

**Comment by lizmat** [comment]
It appears to have stopped again: it didn't mention my upload of Memoize to PAUSE about 30 minutes ago

**Comment by skaji** [comment]
https://www.nntp.perl.org/group/perl.cpan.uploads/

**Comment by lizmat** [comment]
This is what I got from PAUSE by mail:

The uploaded file

   Memoize-0.0.1.tar.gz

has entered CPAN as

 file: $CPAN/authors/id/E/EL/ELIZABETH/Perl6/Memoize-0.0.1.tar.gz
 size: 13623 bytes
  md5: cda813617e1f4dd004c64b0a30f78bf3
 sha1: feb4b3d670ad662192d3b657b75bd2d86e089c98

CPAN Testers will start reporting results in an hour or so:

 http://matrix.cpantesters.org/?dist=Memoize

Request entered by: ELIZABETH (Elizabeth Mattijsen)
Request entered on: Wed, 30 May 2018 12:44:10 GMT
Request completed:  Wed, 30 May 2018 12:45:10 GMT

Thanks,
-- 
paused, v1049

**Comment by lizmat** [comment]
If I check #news on irc.perl.org, I see new uploads that aren't mentioned on that page.  How up to date is that page ??
